Update liveroot

diff --git a/liveroot b/liveroot
--- a/liveroot
+++ b/liveroot
@@ -1,4 +1,4 @@
-#!/usr/bin/sh
+#!/usr/bin/bash
 
 
 create_archive() {
@@ -17,31 +17,62 @@ run_latehook() {
    if read -t 4 -s -n 1; then
 
 
-      echo -e "\nPlease choose an option:\n\n<s>run a snapshot\n<o> run in overlay mode\n<e> extract archive to tmpfs\n<c> copy / directly to tmpfs\n<n> create a new archive file\n<d> enter emergency shell\n<b> continue boot\n"
+      echo -e "\nPlease choose an option:\n\n<s> snapshot mode\n<o> run in overlay mode 1\n<p> run in overlay mode 2\n<e> extract archive to tmpfs\n<c> copy / directly to tmpfs\n<n> create a new archive file\n<d> enter emergency shell\n<b> continue boot\n"
 
       read -n 1 -s key
 
 
-      if [[ "$key" = "o" ]]; then
+      if [[ "$key" = "s" ]]; then
+
+         echo "Premount" 
+         poll_device ${root} 2
+
+         root_dir=/new_root
+
+         mkdir -p $root_dir 
+
+         mount --mkdir -o subvolid=256 ${root} $root_dir
+      
+         btrfs subvolume list -ts $root_dir | less
+         read -n 3 -p "Choose a snapshot (256 is current system): " subvol 
+
+
+         echo -e "\nPlease enter extra mount options (ex., ro ):"
+         read options 
+         [ ! "$options" = "" ] && options=","$options
+
+         echo -e "\nWill proceed with the following mount:\n\nmount -o subvolid=$subvol$options ${root} /\n"
+         sleep 4
+
+         umount $root_dir
+         mount --mkdir -o subvolid=$subvol$options ${root} $root_dir
+
+         if [ "$?" -ne 0 ]; then
+            echo "Couldn't mount that choice. Chosing default (256)."
+            sleep 2
+            mount --mkdir -o subvolid=256 ${root} $root_dir 
+         fi
+
+      elif [[ "$key" = "o" ]]; then
 
          ROOT_MNT="/new_root"
-         OFS_DIRS="/run/archroot"
-         OFS_LOWER="${OFS_DIRS}/root_ro"
-         OFS_COWSPACE="${OFS_DIRS}/cowspace"
-         OFS_UPPER="${OFS_COWSPACE}/upper"
-         OFS_WORK="${OFS_COWSPACE}/work"
+         DIRS="/run/archroot"
+         LOWER="${DIRS}/root_ro"
+         COWSPACE="${DIRS}/cowspace"
+         UPPER="${COWSPACE}/upper"
+         WORK="${COWSPACE}/work"
 
-         mkdir -p ${OFS_LOWER}
-         mount --move ${ROOT_MNT} ${OFS_LOWER}
+         mkdir -p ${LOWER}
+         mount --move ${ROOT_MNT} ${LOWER}
 
-         mkdir -p ${OFS_COWSPACE}
-         mount -t tmpfs cowspace ${OFS_COWSPACE}
+         mkdir -p ${COWSPACE}
+         mount -t tmpfs cowspace ${COWSPACE}
 
-         mkdir -p ${OFS_UPPER} ${OFS_WORK}
+         mkdir -p ${UPPER} ${WORK}
 
-         mount -t overlay -o lowerdir=${OFS_LOWER},upperdir=${OFS_UPPER},workdir=${OFS_WORK} rootfs ${ROOT_MNT}
+         mount -t overlay -o lowerdir=${LOWER},upperdir=${UPPER},workdir=${WORK} rootfs ${ROOT_MNT}
 
-      elif [[ "$key" = "s" ]]; then
+      elif [[ "$key" = "p" ]]; then
  
          local root_mnt="/new_root"
          local lower_dir=$(mktemp -d -p /)
