Update liveroot

diff --git a/liveroot b/liveroot
--- a/liveroot
+++ b/liveroot
@@ -1,133 +1,158 @@
 #!/usr/bin/bash
 
-
 create_archive() {
             
-   echo "Creating archive file..."
-   cd /real_root/@/
+        echo -e "Creating archive file...\n"
 
-   tar --exclude=rootfs.tar.gz --exclude=./.snapshots/* --exclude=./boot/* --exclude=./proc/* --exclude=./run/* --exclude=./dev/* --exclude=./sys/* --exclude=./tmp/* --exclude=./mnt/*  --exclude=./var/tmp/* --exclude=./var/cache/* --exclude=./var/log/* --exclude=./etc/pacman.d/gnupg/* -czf /real_root/@/rootfs.tar.gz . 
+        cd $real_root/@/
+
+        #mksquashfs . $real_root/@/root.squashfs -noappend -no-recovery -mem-percent 50 -e root.squashfs -e boot/* -e efi/* -e dev/* -e proc/* -e sys/* -e tmp/* -e run/* -e mnt/ -e .snapshots/ -e var/tmp/* -e var/cache/* -e var/log/* -e etc/pacman.d/gnupg/ -e var/lib/systemd/random-seed
+        mksquashfs . $real_root/@/root.squashfs -noappend -no-recovery -mem-percent 50 -e root.squashfs -e boot/* -e efi/* -e dev/* -e proc/* -e sys/* -e tmp/* -e run/* -e mnt/ -e .snapshots/ -e var/tmp/* -e var/log/* -e etc/pacman.d/gnupg/ -e var/lib/systemd/random-seed
+
+        ls -la $real_root/@/root.squashfs
+
+}
+
+create_overlay() {
+
+        echo -e "\nCreating overlay...\n"
+
+        local lower_dir=$(mktemp -d -p /)
+        local ram_dir=$(mktemp -d -p /)
+        mount --move ${new_root} ${lower_dir}
+        mount -t tmpfs cowspace ${ram_dir}
+        mkdir -p ${ram_dir}/upper ${ram_dir}/work
+        mount -t overlay -o lowerdir=${lower_dir},upperdir=${ram_dir}/upper,workdir=${ram_dir}/work rootfs ${new_root}
 
 }
 
 
 run_latehook() {
 
-   echo -e "\nPress any key for extra boot options.\n"
 
-   if read -t 3 -s -n 1; then
+        echo -e "\nPress any key for extra boot options.\n"
+
+        real_root=/real_root
+        new_root=/new_root
+        mkdir -p $real_root $new_root
+
+        if read -t 2 -s -n 1; then
+
+                echo -e "\nPlease choose an option:\n\n\
+<s> snapshot\n\
+<w> snapshot + overlay\n\
+<f> snapshot + tmpfs\n\
+<o> overlay\n\
+<e> squashfs + overlay\n\
+<r> squashfs + tmpfs\n\
+<n> create + run squashfs + overlay\n\
+<t> rsync / to tmpfs\n\
+<d> emergency shell\n\n\
+<enter> continue boot\n"
+
+                read -n 1 -s key
 
 
-      echo -e "\nPlease choose an option:\n\n<s> snapshot mode\n<o> run in overlay mode 1\n<p> run in overlay mode 2\n<e> extract archive to tmpfs\n<c> copy / directly to tmpfs\n<n> create a new archive file\n<d> enter emergency shell\n<b> continue boot\n"
 
-      read -n 1 -s key
+                if [[ "$key" = "s" ]] || [[ "$key" = "w" ]] || [[ "$key" = "f" ]]; then
 
-
-      if [[ "$key" = "s" ]]; then
-
-         poll_device ${root} 2
-
-         root_dir=/new_root
-
-         mkdir -p $root_dir 
-
-         mount --mkdir -o subvolid=256 ${root} $root_dir
+                        mount --mkdir -o subvolid=256 ${root} $new_root
       
-         btrfs subvolume list -ts $root_dir | less
-         read -n 3 -p "Choose a snapshot (256 is current system): " subvol 
+                        btrfs subvolume list -ts $new_root | less
+                        read -n 3 -p "Enter snapshot number (or press <enter> for current subvolume (256)): " subvol 
+
+                        if [ ! "$subvol" ]; then
+                                echo -e "\nDefault subvolum chosen.\n"
+                                subvol=256
+                        fi
+
+                        echo -e "\nPlease enter extra mount options (ex., ro ):"
+                        read options 
+                        [ "$options" ] && options=","$options
+
+                        echo -e "\nWill proceed with the following mount:\n\nmount -o subvolid=$subvol$options ${root} /\n"
+
+                        umount $new_root
+                        mount --mkdir -o subvolid=$subvol$options ${root} $new_root
+
+                        if [ "$?" -ne 0 ]; then
+                                echo "Could not mount subvol ($subvol). Chosing default (256)."
+                                sleep 2
+                                mount --mkdir -o subvolid=256 ${root} $new_root 
+                        fi
+
+                        [[ "$key" = "w" ]] && create_overlay
 
 
-         echo -e "\nPlease enter extra mount options (ex., ro ):"
-         read options 
-         [ ! "$options" = "" ] && options=$options","
+                        if [[ "$key" = "f" ]]; then
 
-         echo -e "\nWill proceed with the following mount:\n\nmount -o $options""subvolid=$subvol ${root} /\n"
-         sleep 4
+                                echo "TODO!"
+                                #mount -t tmpfs -o size=80% none $new_root
+                                #rsync -a --exclude=root.squashfs --exclude=/efi/ --exclude=/boot/ --exclude=/dev/ --exclude=/proc/ --exclude=/sys/ --exclude=/tmp/ --exclude=/run/ --exclude=/mnt/ --exclude=/.snapshots/* --exclude=/var/tmp/ --exclude=/var/cache/ --exclude=/var/log/ /real_root/@/ $new_root
+                                #umount -l /real_root
 
-         umount $root_dir
-         mount --mkdir -o "$options"subvolid=$subvol ${root} $root_dir
+                        fi
 
-         if [ "$?" -ne 0 ]; then
-            echo "Could not mount that choice. Chosing default (256)."
-            sleep 2
-            mount --mkdir -o subvolid=256 ${root} $root_dir 
-         fi
+                elif [[ "$key" = "o" ]]; then
 
-      elif [[ "$key" = "o" ]]; then
+                        mount --mkdir -o subvolid=256 ${root} $new_root
 
-         ROOT_MNT="/new_root"
-         DIRS="/run/archroot"
-         LOWER="${DIRS}/root_ro"
-         COWSPACE="${DIRS}/cowspace"
-         UPPER="${COWSPACE}/upper"
-         WORK="${COWSPACE}/work"
+                        create_overlay
 
-         mkdir -p ${LOWER}
-         mount --move ${ROOT_MNT} ${LOWER}
+                elif [[ "$key" = "e" ]] || [[ "$key" = "n" ]] || [[ "$key" = "r" ]]; then
 
-         mkdir -p ${COWSPACE}
-         mount -t tmpfs cowspace ${COWSPACE}
+                                mount ${root} $real_root
 
-         mkdir -p ${UPPER} ${WORK}
+                                [[ ! -f "$real_root/@/root.squashfs" ]] || [[ "$key" = "n" ]] && create_archive
 
-         mount -t overlay -o lowerdir=${LOWER},upperdir=${UPPER},workdir=${WORK} rootfs ${ROOT_MNT}
+                                echo "Extracting archive to RAM. Please be patient..."
 
-      elif [[ "$key" = "p" ]]; then
- 
-         local root_mnt="/new_root"
-         local lower_dir=$(mktemp -d -p /)
-         local ram_dir=$(mktemp -d -p /)
-         mount --move ${root_mnt} ${lower_dir}
-         mount -t tmpfs cowspace ${ram_dir}
-         mkdir -p ${ram_dir}/upper ${ram_dir}/work
-         mount -t overlay -o lowerdir=${lower_dir},upperdir=${ram_dir}/upper,workdir=${ram_dir}/work rootfs ${root_mnt}
+                                if [ "$key" = "r" ]; then
+                                        mount -t tmpfs -o size=80% none $new_root
+                                        unsquashfs -d /new_root -f $real_root/@/root.squashfs
+                                        echo -e "\nYou may now safely remove your USB stick.\n"
+                                        sleep 1
+            else
+                                        mount "$real_root/@/root.squashfs" $new_root -t squashfs -o loop
+                                        create_overlay
+                                fi
 
-      elif [[ "$key" = "e" ]] || [[ "$key" = "n" ]] || [[ "$key" = "c" ]]; then
+                                umount -l $real_root
 
-         poll_device ${root} 2
-         mkdir /real_root/
-         mount ${root} /real_root/
-         mount -t tmpfs -o size=80% none /new_root/
-      
-         if [[ "$key" = "e" ]] || [[ "$key" = "n" ]]; then
+                elif [[ "$key" = "t" ]]; then
 
-            [[ ! -f "/real_root/@/rootfs.tar.gz" ]] || [[ "$key" = "n" ]] && create_archive
+                        mount ${root} $real_root
+                        mount -t tmpfs -o size=80% none $new_root
 
-            echo "Extracting archive to RAM. Please be patient..."
-            tar -xzf /real_root/@/rootfs.tar.gz -C /new_root/
+                        echo "Copying root filesystem to RAM. Please be patient..."
 
-         elif [[ "$key" = "c" ]]; then
+                        rsync -a --exclude=root.squashfs --exclude=/efi/ --exclude=/boot/ --exclude=/dev/ --exclude=/proc/ --exclude=/sys/ --exclude=/tmp/ --exclude=/run/ --exclude=/mnt/ --exclude=/.snapshots/* --exclude=/var/tmp/ --exclude=/var/log/ /real_root/@/ $new_root
 
-            echo "Copying root filesystem to RAM. Please be patient..."
+                        echo -e "\nYou may now safely remove your USB stick.\n"
+                        sleep 1
 
-            #cp -p -a -R /real_root/@/* /new_root/
-            rsync -a --exclude=rootfs.tar.gz --exclude=/dev/ --exclude=/proc/ --exclude=/sys/ --exclude=/tmp/ --exclude=/run/ --exclude=/mnt/ --exclude=/.snapshots/* --exclude=/var/tmp/ --exclude=/var/cache/ --exclude=/var/log/ --exclude=/mnt/ /real_root/@/ /new_root/
+                elif [[ "$key" = "d" ]]; then
 
-         fi
+                        echo "Entering emergency shell."
 
-         touch /new_root/LIVE
-         umount /real_root/
+                        bash
 
-         LIVE_mount() {
-            echo "Live system on RAM."
-         }
-         
-         mount_handler=LIVE_mount
+                else
 
-      elif [[ "$key" = "d" ]]; then
+                        echo "Continuing boot..."
 
-         echo "Entering emergency shell."
+                        umount $new_root
 
-         bash
+                        mount --mkdir -o subvolid=256 ${root} $new_root
+                        mount --uuid $ESP_UUID $new_root/efi
+                fi
 
-      elif [[ "$key" = "b" ]]; then
+        else
 
-         echo "Continuing boot..."
+                echo -e "Running default option..."
 
-      fi
+                mount --uuid $ESP_UUID $new_root/efi
 
-   fi
+        fi
+
 }
-
-
-
